const src = require('./harness.js').src;
eval(src+`;
begin(); let errs=0; const run=n=>{for(let k=0;k<n;k++){ try{update(1/60);draw();}catch(e){errs++; if(errs<4) console.log('ERR',e.message);} }}; const press=(k,n=1)=>{ state.keys[k]=true; run(n); state.keys[k]=false; run(2); };
const clear=()=>{ for(let i=0;i<12 && (state.texts.some(t=>t.hold)||(state.title&&state.title.hold));i++) press('f',1); };
const h=state.hero, inv=state.inv;
run(10); for(let i=0;i<3;i++){ press('f'); run(20);} for(let k=0;k<60*14 && state.intro;k++) run(1); clear();
const said=[]; const _s=say; say=function(t,x,y,o){ if(o&&o.key==='pip') { const sp=(WORLD.camp.feat.buildSpots||[]).map(b=>[b.piece, Math.hypot(state.pip.x-b.fx*W, state.pip.y-b.fy*H)/UNIT]).sort((a,b)=>a[1]-b[1])[0]; said.push(t+'   [Pip by the '+(sp&&sp[1]<2.2?sp[0]+' mark':'-')+']'); } return _s(t,x,y,o); };
inv.story=STORY.gather; enterScene('camp'); rtFor('camp').flags.built_tent=true; const R=rawOf(); for(const k in R) R[k]=0;
const stage=(label, fn)=>{ fn(); state.pipTalkT=-99; const n0=said.length; for(let k=0;k<60*12 && said.length===n0;k++){ run(1); if(state.pip && state.pip.visit){ const v=state.pip.visit; h.x=v.x+UNIT*1.5; h.y=v.y+UNIT; } } console.log(label.padEnd(26), '->', said.slice(n0).join(' / ')||'(nothing)'); };
h.x=W*0.5; h.y=H*0.7;
stage('nothing gathered', ()=>{});
stage('2 stones', ()=>{ R.stone=2; });
stage('2 stones, a stick', ()=>{ R.stick=1; });
stage('fire ring crafted', ()=>{ R.stone=0; R.stick=0; R.firering=1; });
stage('fire built', ()=>{ R.firering=0; rtFor('camp').flags.built_fire=true; });
stage('2 sticks, 2 fluff', ()=>{ R.stick=2; R.fluff=2; });
stage('glue made', ()=>{ R.fluff=0; R.glue=1; });
stage('bench kit made', ()=>{ R.stick=0; R.glue=0; R.benchkit=1; });
console.log('longest line', Math.max(...said.map(s=>s.split('   [')[0].length)), 'characters');
console.log('BUILD', BUILD, '| errs', errs);
`);
