const src = require('./harness.js').src;
eval(src+`;
begin(); let errs=0; const run=n=>{for(let k=0;k<n;k++){ try{update(1/60);draw();}catch(e){errs++; if(errs<4) console.log('ERR',e.message);} }}; const press=(k,n=1)=>{ state.keys[k]=true; run(n); state.keys[k]=false; run(2); };
const clear=()=>{ for(let i=0;i<12 && (state.texts.some(t=>t.hold)||(state.title&&state.title.hold));i++) press('f',1); };
run(5); state.intro=null; state.texts=[]; enterScene('start'); state.enemies=[]; run(5); const inv=state.inv, h=state.hero, sl=()=>JSON.stringify(Object.fromEntries(ALL_SLOTS.map(k=>[k, slotsOf()[k]?slotsOf()[k].id:null])));
const give=t=>{ collect({type:t,x:h.x,y:h.y}); run(20); };
give('turnipseed'); give('turnip'); give('acorn'); inv.woodsword=WOOD_SWORD; run(20);
console.log('1 lanes: seeds, food, acorns, blade ->', sl());
give('carrot'); give('carrotseed'); console.log('2 a second food and a second seed stay in the pack (their keys are taken):', sl());
state.texts=[]; h.vig=2; const t0=inv.food.filter(f=>f==='turnip').length; press('s'); console.log('3 tap S eats the turnip:', inv.food.filter(f=>f==='turnip').length===t0-1);
inv.food.push('turnip'); run(20); state.keys.s=true; run(20); const R=state.radial; console.log('4 hold S: wheel', R&&R.lane, R&&R.opts.map(o=>o.id).join(','));
R.sel=R.opts.findIndex(o=>o.id==='carrot'); state.keys.s=false; run(3); console.log('   let go on carrot: S =', slotsOf().s&&slotsOf().s.id, '| wheel closed', !state.radial, '| nothing eaten by the hold', inv.food.includes('turnip'));
state.keys.a=true; run(20); console.log('5 hold A: seeds wheel', state.radial&&state.radial.opts.map(o=>o.id).join(',')); state.keys.a=false; run(3);
console.log('BUILD', BUILD, '| errs', errs);
`);
