const src = require('./harness.js').src;
eval(src+`;
begin(); let errs=0; const run=n=>{for(let k=0;k<n;k++){ try{update(1/60);draw();}catch(e){errs++; if(errs<4) console.log('ERR',e.message);} }}; const press=(k,n=1)=>{ state.keys[k]=true; run(n); state.keys[k]=false; run(2); };
run(10); state.intro=null; state.texts=[]; enterScene('riverbank'); run(5);
console.log('1 pickup nudge:', JSON.stringify(ZP.pickup));
console.log('2 tabs at the start:', PACK_TABS.filter(tabShown).join(', '));
const inv=state.inv; inv.food.push('turnip'); inv.bag.turnipseed=1; gainGear('feather',true); state.title=null; console.log('   with food, seeds and a feather:', PACK_TABS.filter(tabShown).join(', '));
inv.sword=true; inv.acorns=3; inv.fire=true; inv.step=1; inv.up.edge=1; inv.rod=true; const cs=packCells('Gear'); console.log('3 Gear sections:', cs.map(c=>c.sec+':'+c.icon).join(' '), '| no farming cell', !cs.some(c=>/Farming/.test(c.name)));
state.menu={view:'pack',tab:0,sel:0,focus:'grid',act:0,sys:0,note:''}; run(1); press('arrowdown'); const s1=state.menu.sel; press('arrowdown'); const s2=state.menu.sel; press('arrowup'); press('arrowup'); press('arrowup');
console.log('4 down goes by section rows:', cs[0].icon+' -> '+cs[s1].icon+' -> '+cs[s2].icon, '| up from the top row goes to the tabs', state.menu.focus);
state.menu.focus='tabs'; state.menu.tab=0; const seq=[]; for(let i=0;i<10;i++){ press('arrowright'); seq.push(PACK_TABS[state.menu.tab]); } console.log('5 right through the tabs:', seq.join(' > '));
console.log('6 Status rows:', statusRows().filter(r=>r[0]==='head').map(r=>r[1]).join(', '), '|', statusRows().filter(r=>r[0]==='skill').map(r=>r[1]+' '+r[2]+'/'+r[3]).join(', '));
state.menu={view:'pack',tab:PACK_TABS.indexOf('System'),sel:0,focus:'grid',act:0,sys:SYSTEM_ITEMS().findIndex(o=>o[0]==='levels'),note:''}; press('f'); console.log('7 System > Testing opens:', state.menu.view);
state.menu.sel=LEVEL_ROWS().findIndex(r=>/Gather/.test(r.label)); press('arrowright'); press('arrowright'); press('f'); console.log('   gather after right, right, F:', skillLevel('gather')); press('arrowleft'); console.log('   left:', skillLevel('gather'));
state.menu.sel=LEVEL_ROWS().findIndex(r=>/top/.test(r.label)); press('f'); console.log('   everything to the top:', Object.keys(SKILLS).map(k=>k+' '+skillLevel(k)).join(', '));
state.menu.sel=LEVEL_ROWS().findIndex(r=>/Vigor depth/.test(r.label)); press('arrowright'); console.log('   vigor depth', inv.depth, 'max vigor', maxVig());
press('d'); console.log('8 D goes back to System:', state.menu&&state.menu.view, PACK_TABS[state.menu.tab]);
console.log('BUILD', BUILD, '| errs', errs);
`);
