const src=require('fs').readFileSync('/mnt/user-data/outputs/index.html','utf8').match(/<script>([\s\S]*)<\/script>/)[1];
const noop=()=>{}; const grad={addColorStop:(o,c)=>{ if(!(o>=0&&o<=1)) throw new Error('colorstop offset '+o); if(/NaN|undefined|Infinity/.test(String(c))) throw new Error('bad color '+c); }};
const chk=(name,vals)=>{ for(const v of vals) if(!(isFinite(v))) throw new Error(name+' non-finite '+vals.join(',')); };
const mkctx=()=>new Proxy({},{get:(t,k)=>{ if(k in t) return t[k];
 if(k==='measureText') return (s)=>({width:s.length*8});
 if(k==='arc') return (x,y,r)=>{ chk('arc',[x,y,r]); if(r<0) throw new Error('arc negative radius '+r); };
 if(k==='ellipse') return (x,y,rx,ry)=>{ chk('ellipse',[x,y,rx,ry]); if(rx<0||ry<0) throw new Error('ellipse negative radius '+rx+','+ry); };
 if(k==='createRadialGradient') return (x0,y0,r0,x1,y1,r1)=>{ chk('radial',[x0,y0,r0,x1,y1,r1]); if(r0<0||r1<0) throw new Error('radial negative '+r0+','+r1); return grad; };
 if(k==='createLinearGradient') return (a,b,c,d)=>{ chk('linear',[a,b,c,d]); return grad; };
 if(k==='addColorStop') return noop;
 if(k.startsWith('create')) return ()=>grad; return noop; },set:(t,k,v)=>(t[k]=v,true)});
const el=()=>({addEventListener:noop,getContext:mkctx,remove:noop,style:{},classList:{toggle:noop},dataset:{}});
const P=()=>{const param={value:0,setValueAtTime(){},linearRampToValueAtTime(){},exponentialRampToValueAtTime(){},setTargetAtTime(){},cancelScheduledValues(){}};
 return new Proxy({},{get:(t,k)=>{ if(k in t) return t[k]; if(['gain','frequency','Q','pan'].includes(k)) return t[k]=param; if(k==='connect') return (n)=>n||P(); if(k==='getChannelData') return ()=>new Float32Array(10); return ()=>P(); }, set:(t,k,v)=>(t[k]=v,true)});};
class AC{constructor(){this.currentTime=0;this.sampleRate=100;this.state='running';this.destination=P();} createGain(){return P()} createOscillator(){return P()} createBufferSource(){return P()} createBiquadFilter(){return P()} createStereoPanner(){return P()} createBuffer(){return P()} resume(){}}
global.document={getElementById:el,querySelectorAll:()=>[],createElement:el,documentElement:{},addEventListener:noop};
global.window={AudioContext:AC,innerWidth:1280,innerHeight:800,devicePixelRatio:1,addEventListener:noop,matchMedia:()=>({matches:false})};
const store={}; global.localStorage={getItem:k=>store[k]??null,setItem:(k,v)=>{store[k]=String(v)}};
global.setTimeout=(f)=>{f()}; global.setInterval=noop; global.requestAnimationFrame=noop; global.performance={now:()=>0};
eval(src+`;
let errs=0; const run=(n)=>{ for(let k=0;k<n;k++){ try{ update(1/60); draw(); }catch(e){ errs++; if(errs<6) console.log('ERR', state.scene, e.message, String(e.stack).slice(0,300)); return; } } };
const said=[]; const st0=showTitle; showTitle=function(t,sub,a,b){ if(/quest/i.test(t)) said.push(t+': '+sub); return st0(t,sub,a,b); };
begin(); state.cut=null; const inv=state.inv; run(3);
const cur=()=>questView().cur.map(c=>c.q.name+': '+c.step.name).join(' | ')||'(none)';
const logs=()=>questView().log.map(e=>e.st.name+(e.last?' [done]':'')).join(' < ');
const tick=(n=20)=>{ state.playTime+=5; run(n); };
console.log('before the garden:', cur());
inv.story=STORY.garden; tick(); console.log('1', cur());
inv.bag.seed=1; tick(); console.log('2', cur());
const plots=rtFor('meadow').flags.plots||(rtFor('meadow').flags.plots=WORLD.meadow.feat.plots.map(()=>({s:0,t:0,lv:0})));
plots[0].s=1; inv.bag.seed=0; tick(); console.log('3 one planted:', cur(), '|', questView().cur[0].step.line());
plots[1].s=1; inv.story=STORY.tocamp; tick(); console.log('4 two planted:', cur());
inv.story=STORY.gather; tick(); console.log('5 at camp:', cur());
const raw=rawOf(); raw.stone=2; raw.stick=1; tick(); console.log('6', questView().cur.find(c=>c.q.id==='camp').step.line());
raw.fluff=2; raw.stick=3; tick(); console.log('7 gathered:', cur());
rtFor('camp').flags.built_fire=true; tick(); rtFor('camp').flags.built_bench=true; tick(); console.log('8 camp built:', cur());
inv.harvests=1; tick(); console.log('9 harvested:', cur());
console.log('log newest first:', logs());
console.log('announcements:', JSON.stringify(said));
console.log('each step logged once:', inv.qlog.length, '=', 3+4, '| times', inv.qlog.map(e=>e.t).join(','));
// menu: Quests tab, fold/unfold
toggleMenu(); const m=state.menu; m.tab=PACK_TABS.indexOf('Quests'); m.focus='tabs'; run(1);
state.keys.arrowdown=true; run(1); state.keys.arrowdown=false; run(1);
console.log('rows folded:', questRows(questView()).map(r=>r.kind).join(','), '| sel', m.qsel);
state.keys.arrowdown=true; run(1); state.keys.arrowdown=false; run(1);
const actKey=Object.entries(state.settings.keys||DEFAULT_KEYS).find(([a])=>a==='act'); state.keys[(actKey&&actKey[1])||'f']=true; run(1); state.keys[(actKey&&actKey[1])||'f']=false; run(1);
console.log('after F on the log row: open', !!state.qlogOpen, '| rows', questRows(questView()).length);
toggleMenu();
// old save: story already at gather with a fire ring: filed quietly, no announcements, times blank
said.length=0; const save=JSON.parse(JSON.stringify(serialize())); delete save.inv.quests; delete save.inv.qlog; save.inv.harvests=0; save.inv.cropXp={}; save.rt.camp.flags={built_fire:true,built_tent:true};
localStorage.setItem('quest-slot-2', JSON.stringify(save)); loadSlot(2); run(30);
console.log('old save:', cur(), '| log', state.inv.qlog.length, 'entries, times', JSON.stringify(state.inv.qlog.map(e=>e.t)), '| announcements', said.length);
state.inv.harvests=1; state.playTime+=5; run(20); console.log('then a harvest:', JSON.stringify(said), '| newest log', questView().log[0].st.name, clock(questView().log[0].t));
console.log('BUILD', BUILD, '| errs', errs);
`);
