const src=require('fs').readFileSync('/mnt/user-data/outputs/index.html','utf8').match(/<script>([\s\S]*)<\/script>/)[1];
const noop=()=>{}; const grad={addColorStop:(o,c)=>{ if(!(o>=0&&o<=1)) throw new Error('colorstop offset '+o); if(/NaN|undefined|Infinity/.test(String(c))) throw new Error('bad color '+c); }};
const chk=(name,vals)=>{ for(const v of vals) if(!(isFinite(v))) throw new Error(name+' non-finite '+vals.join(',')); };
const mkctx=()=>new Proxy({},{get:(t,k)=>{ if(k in t) return t[k];
 if(k==='measureText') return (s)=>({width:s.length*8});
 if(k==='arc') return (x,y,r)=>{ chk('arc',[x,y,r]); if(r<0) throw new Error('arc negative radius '+r); };
 if(k==='ellipse') return (x,y,rx,ry)=>{ chk('ellipse',[x,y,rx,ry]); if(rx<0||ry<0) throw new Error('ellipse negative radius '+rx+','+ry); };
 if(k==='createRadialGradient') return (x0,y0,r0,x1,y1,r1)=>{ chk('radial',[x0,y0,r0,x1,y1,r1]); if(r0<0||r1<0) throw new Error('radial negative '+r0+','+r1); return grad; };
 if(k==='createLinearGradient') return (a,b,c,d)=>{ chk('linear',[a,b,c,d]); return grad; };
 if(k==='addColorStop') return noop;
 if(k.startsWith('create')) return ()=>grad; return noop; },set:(t,k,v)=>(t[k]=v,true)});
const el=()=>({addEventListener:noop,getContext:mkctx,remove:noop,style:{},classList:{toggle:noop},dataset:{}});
const P=()=>{const param={value:0,setValueAtTime(){},linearRampToValueAtTime(){},exponentialRampToValueAtTime(){},setTargetAtTime(){},cancelScheduledValues(){}};
 return new Proxy({},{get:(t,k)=>{ if(k in t) return t[k]; if(['gain','frequency','Q','pan'].includes(k)) return t[k]=param; if(k==='connect') return (n)=>n||P(); if(k==='getChannelData') return ()=>new Float32Array(10); return ()=>P(); }, set:(t,k,v)=>(t[k]=v,true)});};
class AC{constructor(){this.currentTime=0;this.sampleRate=100;this.state='running';this.destination=P();} createGain(){return P()} createOscillator(){return P()} createBufferSource(){return P()} createBiquadFilter(){return P()} createStereoPanner(){return P()} createBuffer(){return P()} resume(){}}
global.document={getElementById:el,querySelectorAll:()=>[],createElement:el,documentElement:{},addEventListener:noop};
global.window={AudioContext:AC,innerWidth:1280,innerHeight:800,devicePixelRatio:1,addEventListener:noop,matchMedia:()=>({matches:false})};
const store={}; global.localStorage={getItem:k=>store[k]??null,setItem:(k,v)=>{store[k]=String(v)}};
global.setTimeout=(f)=>{f()}; global.setInterval=noop; global.requestAnimationFrame=noop; global.performance={now:()=>0};
eval(src+`;
begin(); let errs=0; const run=n=>{for(let k=0;k<n;k++){ try{update(1/60);draw();}catch(e){errs++; if(errs<4) console.log('ERR',e.message);} }}; const press=(k,n=1)=>{ state.keys[k]=true; run(n); state.keys[k]=false; run(2); };
run(10); state.intro=null; state.texts=[]; enterScene('riverbank'); run(5);
console.log('1 pickup nudge:', JSON.stringify(ZP.pickup));
console.log('2 tabs at the start:', PACK_TABS.filter(tabShown).join(', '));
const inv=state.inv; inv.food.push('turnip'); inv.bag.turnipseed=1; gainGear('feather',true); state.title=null; console.log('   with food, seeds and a feather:', PACK_TABS.filter(tabShown).join(', '));
inv.sword=true; inv.acorns=3; inv.fire=true; inv.step=1; inv.up.edge=1; inv.rod=true; const cs=packCells('Gear'); console.log('3 Gear sections:', cs.map(c=>c.sec+':'+c.icon).join(' '), '| no farming cell', !cs.some(c=>/Farming/.test(c.name)));
state.menu={view:'pack',tab:0,sel:0,focus:'grid',act:0,sys:0,note:''}; run(1); press('arrowdown'); const s1=state.menu.sel; press('arrowdown'); const s2=state.menu.sel; press('arrowup'); press('arrowup'); press('arrowup');
console.log('4 down goes by section rows:', cs[0].icon+' -> '+cs[s1].icon+' -> '+cs[s2].icon, '| up from the top row goes to the tabs', state.menu.focus);
state.menu.focus='tabs'; state.menu.tab=0; const seq=[]; for(let i=0;i<10;i++){ press('arrowright'); seq.push(PACK_TABS[state.menu.tab]); } console.log('5 right through the tabs:', seq.join(' > '));
console.log('6 Status rows:', statusRows().filter(r=>r[0]==='head').map(r=>r[1]).join(', '), '|', statusRows().filter(r=>r[0]==='skill').map(r=>r[1]+' '+r[2]+'/'+r[3]).join(', '));
state.menu={view:'pack',tab:PACK_TABS.indexOf('System'),sel:0,focus:'grid',act:0,sys:SYSTEM_ITEMS().findIndex(o=>o[0]==='levels'),note:''}; press('f'); console.log('7 System > Testing opens:', state.menu.view);
state.menu.sel=LEVEL_ROWS().findIndex(r=>/Gather/.test(r.label)); press('arrowright'); press('arrowright'); press('f'); console.log('   gather after right, right, F:', skillLevel('gather')); press('arrowleft'); console.log('   left:', skillLevel('gather'));
state.menu.sel=LEVEL_ROWS().findIndex(r=>/top/.test(r.label)); press('f'); console.log('   everything to the top:', Object.keys(SKILLS).map(k=>k+' '+skillLevel(k)).join(', '));
state.menu.sel=LEVEL_ROWS().findIndex(r=>/Vigor depth/.test(r.label)); press('arrowright'); console.log('   vigor depth', inv.depth, 'max vigor', maxVig());
press('d'); console.log('8 D goes back to System:', state.menu&&state.menu.view, PACK_TABS[state.menu.tab]);
console.log('BUILD', BUILD, '| errs', errs);
`);
