const src=require('fs').readFileSync('/mnt/user-data/outputs/index.html','utf8').match(/<script>([\s\S]*)<\/script>/)[1];
const noop=()=>{}; const grad={addColorStop:(o,c)=>{ if(!(o>=0&&o<=1)) throw new Error('colorstop offset '+o); if(/NaN|undefined|Infinity/.test(String(c))) throw new Error('bad color '+c); }};
const chk=(name,vals)=>{ for(const v of vals) if(!(isFinite(v))) throw new Error(name+' non-finite '+vals.join(',')); };
const mkctx=()=>new Proxy({},{get:(t,k)=>{ if(k in t) return t[k];
 if(k==='measureText') return (s)=>({width:s.length*8});
 if(k==='arc') return (x,y,r)=>{ chk('arc',[x,y,r]); if(r<0) throw new Error('arc negative radius '+r); };
 if(k==='ellipse') return (x,y,rx,ry)=>{ chk('ellipse',[x,y,rx,ry]); if(rx<0||ry<0) throw new Error('ellipse negative radius '+rx+','+ry); };
 if(k==='createRadialGradient') return (x0,y0,r0,x1,y1,r1)=>{ chk('radial',[x0,y0,r0,x1,y1,r1]); if(r0<0||r1<0) throw new Error('radial negative '+r0+','+r1); return grad; };
 if(k==='createLinearGradient') return (a,b,c,d)=>{ chk('linear',[a,b,c,d]); return grad; };
 if(k==='addColorStop') return noop;
 if(k.startsWith('create')) return ()=>grad; return noop; },set:(t,k,v)=>(t[k]=v,true)});
const el=()=>({addEventListener:noop,getContext:mkctx,remove:noop,style:{},classList:{toggle:noop},dataset:{}});
const P=()=>{const param={value:0,setValueAtTime(){},linearRampToValueAtTime(){},exponentialRampToValueAtTime(){},setTargetAtTime(){},cancelScheduledValues(){}};
 return new Proxy({},{get:(t,k)=>{ if(k in t) return t[k]; if(['gain','frequency','Q','pan'].includes(k)) return t[k]=param; if(k==='connect') return (n)=>n||P(); if(k==='getChannelData') return ()=>new Float32Array(10); return ()=>P(); }, set:(t,k,v)=>(t[k]=v,true)});};
class AC{constructor(){this.currentTime=0;this.sampleRate=100;this.state='running';this.destination=P();} createGain(){return P()} createOscillator(){return P()} createBufferSource(){return P()} createBiquadFilter(){return P()} createStereoPanner(){return P()} createBuffer(){return P()} resume(){}}
global.document={getElementById:el,querySelectorAll:()=>[],createElement:el,documentElement:{},addEventListener:noop};
global.window={AudioContext:AC,innerWidth:1280,innerHeight:800,devicePixelRatio:1,addEventListener:noop,matchMedia:()=>({matches:false})};
const store={}; global.localStorage={getItem:k=>store[k]??null,setItem:(k,v)=>{store[k]=String(v)}};
global.setTimeout=(f)=>{f()}; global.setInterval=noop; global.requestAnimationFrame=noop; global.performance={now:()=>0};
eval(src+`;
begin(); let errs=0; const run=n=>{for(let k=0;k<n;k++){ try{update(1/60);draw();}catch(e){errs++; if(errs<4) console.log('ERR',e.message);} }}; const press=(k,n=1)=>{ state.keys[k]=true; run(n); state.keys[k]=false; run(2); };
const clear=()=>{ for(let i=0;i<12 && (state.texts.some(t=>t.hold)||(state.title&&state.title.hold));i++) press('f',1); };
run(5); state.intro=null; state.texts=[]; enterScene('start'); state.enemies=[]; run(5); const inv=state.inv, h=state.hero, sl=()=>JSON.stringify(Object.fromEntries(ALL_SLOTS.map(k=>[k, slotsOf()[k]?slotsOf()[k].id:null])));
const give=t=>{ collect({type:t,x:h.x,y:h.y}); run(20); };
give('turnipseed'); give('turnip'); give('acorn'); inv.woodsword=WOOD_SWORD; run(20);
console.log('1 lanes: seeds, food, acorns, blade ->', sl());
give('carrot'); give('carrotseed'); console.log('2 a second food and a second seed stay in the pack (their keys are taken):', sl());
state.texts=[]; h.vig=2; const t0=inv.food.filter(f=>f==='turnip').length; press('s'); console.log('3 tap S eats the turnip:', inv.food.filter(f=>f==='turnip').length===t0-1);
inv.food.push('turnip'); run(20); state.keys.s=true; run(20); const R=state.radial; console.log('4 hold S: wheel', R&&R.lane, R&&R.opts.map(o=>o.id).join(','));
R.sel=R.opts.findIndex(o=>o.id==='carrot'); state.keys.s=false; run(3); console.log('   let go on carrot: S =', slotsOf().s&&slotsOf().s.id, '| wheel closed', !state.radial, '| nothing eaten by the hold', inv.food.includes('turnip'));
state.keys.a=true; run(20); console.log('5 hold A: seeds wheel', state.radial&&state.radial.opts.map(o=>o.id).join(',')); state.keys.a=false; run(3);
console.log('BUILD', BUILD, '| errs', errs);
`);
